groups:
  - name: masark_alerts
    rules:
      - alert: HighCPUUsage
        expr: cpu_usage_active > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage detected"
          description: "CPU usage is above 80% for more than 5 minutes"
          
      - alert: HighMemoryUsage
        expr: mem_used_percent > 85
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage detected"
          description: "Memory usage is above 85% for more than 5 minutes"
          
      - alert: ApplicationDown
        expr: up{job="masark-api"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Masark API is down"
          description: "The Masark API application is not responding"
          
      - alert: DatabaseConnectionFailed
        expr: up{job="sql-server"} == 0
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "Database connection failed"
          description: "Cannot connect to SQL Server database"
          
      - alert: RedisConnectionFailed
        expr: up{job="redis"} == 0
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "Redis connection failed"
          description: "Cannot connect to Redis cache"
          
      - alert: HighResponseTime
        expr: http_request_duration_seconds{quantile="0.95"} > 2
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High response time detected"
          description: "95th percentile response time is above 2 seconds"
          
      - alert: HighErrorRate
        expr: rate(http_requests_total{status=~"5.."}[5m]) > 0.1
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High error rate detected"
          description: "Error rate is above 10% for the last 5 minutes"
          
      - alert: DiskSpaceRunningOut
        expr: disk_used_percent > 90
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Disk space running out"
          description: "Disk usage is above 90%"
          
      - alert: TooManyConnections
        expr: rate(http_requests_total[1m]) > 1000
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High request rate detected"
          description: "Request rate is above 1000 requests per minute"
