global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: 'masark-api'
    static_configs:
      - targets: ['masark-api:8080']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s
    
  - job_name: 'masark-health'
    static_configs:
      - targets: ['masark-api:8080']
    metrics_path: '/health'
    scrape_interval: 10s
    scrape_timeout: 5s
    
  - job_name: 'redis'
    static_configs:
      - targets: ['masark-redis:6379']
    
  - job_name: 'sql-server'
    static_configs:
      - targets: ['masark-db:1433']
    
  - job_name: 'nginx'
    static_configs:
      - targets: ['masark-nginx:80']
    
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
